logging: aim
log_repo: aim://172.31.62.192:53800
seed: 3
episodes: 1000
patience: 1000
env_params:
  env_name: brax-hopper
  batch_size: 1
  init_kwargs:
    backend: spring
trace_mode: accumulate
gamma: 0.99
lambda_v: 0.95
lambda_pi: 0.97
lambda_rnn: 0.97
entropy_rate: 1.0e-05
steps: 1000
eval_every: 50
pass_obs: false
optimizer_params_td:
  learning_rate: 3.0e-05
optimizer_params_rnn:
  learning_rate: 3.0e-05
eta_pi: 3.0
eta_f: 0.0
normalize_obs: false
normalize_reward: true
