logging: aim
log_repo: aim://172.31.62.192:53800
seed: 3
episodes: 250
patience: 250
env_params:
  env_name: brax-hopper
  batch_size: 4
  init_kwargs:
    backend: spring
trace_mode: dutch
gamma: 0.85
lambda_v: 0.97
lambda_pi: 0.975
lambda_rnn: 0.945
entropy_rate: 1.0e-07
steps: 1000
eval_every: 12
pass_obs: true
optimizer_params_td:
  learning_rate: 0.001
optimizer_params_rnn:
  learning_rate: 3.0e-05
update_period: 0.01
eta_pi: 1.0
eta_f: 0.6
normalize_obs: false
normalize_reward: false
run_name: RTRRL-HOP-385
