logging: aim
log_repo: aim://172.31.62.192:53800
seed: 3
episodes: 63
patience: 63
env_params:
  env_name: brax-hopper
  batch_size: 16
  init_kwargs:
    backend: spring
trace_mode: accumulate
gamma: 0.95
lambda_v: 0.95
lambda_pi: 0.97
lambda_rnn: 0.96
entropy_rate: 0.0007
steps: 1000
eval_every: 3
pass_obs: false
optimizer_params_td:
  learning_rate: 5.0e-05
optimizer_params_rnn:
  learning_rate: 2.0e-06
update_period: 0.11
eta_pi: 0.35
eta_f: 0.1
normalize_obs: true
normalize_reward: true
