logging: "aim"
log_repo: ".aim"
run_name: "PPO-HC-038-env256-3M"
seed: 3
env_params:
  env_name: "brax-halfcheetah"
  obs_mask: [0, 2, 4, 6, 8, 10, 12, 14, 16]
  max_ep_length: 1000
  init_kwargs:
    backend: "spring"
num_timesteps: 3000000
ppo_overrides:
  num_evals: 10
  reward_scaling: 1
  action_repeat: 1
  normalize_observations: true
  unroll_length: 1
  num_minibatches: 16
  num_updates_per_batch: 8
  discounting: 0.95
  learning_rate: 0.0003
  entropy_cost: 0.001
  num_envs: 256
  batch_size: 256
