logging: aim
log_repo: aim://172.31.62.192:53800
seed: 3
episodes: 63
patience: 63
env_params:
  env_name: brax-hopper
  batch_size: 16
  init_kwargs:
    backend: spring
trace_mode: accumulate
gamma: 0.99
lambda_v: 0.9
lambda_pi: 0.93
lambda_rnn: 0.9
entropy_rate: 3.0e-05
steps: 1000
eval_every: 3
pass_obs: true
optimizer_params_td:
  learning_rate: 0.003
optimizer_params_rnn:
  learning_rate: 3.0e-05
update_period: 0.5
eta_pi: 0.3
eta_f: 0.2
normalize_obs: false
normalize_reward: true
run_name: RTRRL-HOP-249
