logging: aim
log_repo: aim://172.31.62.192:53800
run_name: advisor/ppo-hc038-env2048-v1/r001-001
seed: 3
env_params:
  env_name: brax-halfcheetah
  obs_mask:
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  - 16
  max_ep_length: 1000
  init_kwargs:
    backend: spring
num_timesteps: 10000000
ppo_overrides:
  num_evals: 10
  reward_scaling: 1
  action_repeat: 1
  normalize_observations: true
  unroll_length: 1
  num_minibatches: 64
  num_updates_per_batch: 8
  discounting: 0.9621934363250151
  learning_rate: 0.00035384535909065536
  entropy_cost: 0.00808164905785623
  num_envs: 2048
  batch_size: 512
